# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/validate
Content-Type: application/json

{
    "login": "aaleem.bscs21seecs",
    "password": "Student.123"
}

###

POST http://127.0.0.1:8000/addUser
Content-Type: application/json

{
    "login": "aaleem.bscs21seecs",
    "password": "Student.123",
  "section": "A"
}

###

POST 127.0.0.1:8000/getTerms
Content-Type: application/json

{
"login": "aaleem.bscs21seecs"
}

###
POST 127.0.0.1:8000/getGrades
Content-Type: application/json

{
"login": "aaleem.bscs21seecs",
"term": "fall 2021"
}

###
POST 127.0.0.1:8000/getImage
Content-Type: application/json

{
"login": "aaleem.bscs21seecs",
"term": "fall 2021",
  "subject": "CS-110"
}